package com.linfq.chat.model;

import com.linfq.chat.common.orm.BaseModel;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table friend_request
 */
public class FriendRequest extends BaseModel {

    /**
     * send_user_id
     */
    private Integer sendUserId;

    /**
     * accept_user_id
     */
    private Integer acceptUserId;

}