package com.linfq.chat.model;

import com.linfq.chat.common.orm.BaseModel;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table my_friend
 */
public class MyFriend extends BaseModel {

    /**
     * my_user_id
     */
    private Integer myUserId;

    /**
     * my_friend_user_id
     */
    private Integer myFriendUserId;

}