package com.linfq.chat.model;

import com.linfq.chat.common.orm.BaseModel;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 */
public class User extends BaseModel {

    /**
     * username
     */
    private String username;

    /**
     * password
     */
    private String password;

    /**
     * face_image
     */
    private String faceImage;

    /**
     * face_image_big
     */
    private String faceImageBig;

    /**
     * nickname
     */
    private String nickname;

    /**
     * qrcode
     */
    private String qrcode;

    /**
     * client_id
     * cid
     */
    private String cid;

}